# Generated by Django 4.1.3 on 2022-11-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_company_content_company_location_item_tip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='head_image',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default=1, upload_to='shop/images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
