# Generated by Django 4.1.3 on 2022-12-17 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_item_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='like_users',
        ),
        migrations.AddField(
            model_name='item',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
