# Generated by Django 4.1.3 on 2022-12-18 13:47

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_item_like_remove_item_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
